module.exports = {
  app: require("./app.json"),
  burgerMenu: require("./burgerMenu.js"),
  burgerMenuLink: require("./burgerMenuLink.js"),
  chooseFormat: require("./chooseFormat.js"),
  choosePhoto: require("./choosePhoto.js"),
  chooseWatermark: require("./chooseWatermark.js"),
  configureWatermark: require("./configureWatermark.js"),
  create: require("./create.js"),
  footer: require("./footer.js"),
  generate: require("./generate.js"),
  header: require("./header.js"),
  loadingbar: require("./loadingbar.json"),
  router: require("./router.json"),
  start: require("./start.js"),
}